config/routes.rb
Rails.application.routes.draw do
  get 'user/show'

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,
    controllers: { registrations: 'registrations',
                   omniauth_callbacks: 'users/omniauth_callbacks'
                 }
  root to: 'pages#home'

  resources :recommendations do
    resources :bookmarks, only: [:create, :index, :delete]
  end

  get 'users/:id/show', to: 'users#show', as: 'user_profile'
  get 'users/:id/bookmarks', to: 'users#user_bookmarks', as: 'user_bookmarks'
  get 'users/:id/ratings', to: 'users#user_ratings', as: 'user_ratings'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recommendations, only: [ :create ]
    end
  end

end

app/views/shared/_bookmarks.html.erb
<%= link_to recommendation_path(r), :class => "link" do%>


<div class="card">
  <div class="card-body">
    <div class="card-picture" style="background-image: url('<%= cl_image_path(r.photo, width: 500, height: 300) %>')">
      <div class="card-hover">
        <ul class="list-inline text-center hover-btns">
          <li>
            <%= link_to "http://maps.google.com/maps?saddr=#{params[:latitude]},#{params[:longitude]}&daddr=#{r.latitude},#{r.longitude}&ie=UTF8&dirflg=w", :target => '_blank'  do %>
              <i class="fa fa-map"></i>
            <% end %>
            <h3>Go there</h3>
          </li>
          <li>
            <%= link_to recommendation_path(r)  do %>
              <i class="fa fa-eye"></i>
            <% end %>
            <h3>More infos</h3>
          </li>
        </ul>

      </div>
    </div>
    <div class="card-infos">
      <div class="card-title">
        <h3><%= r.name.truncate(25) + "..." %></h3>
        <p class="rating"><%= rating_for r, "rating", disabled: true, star_path: '/images/ratyrate' %></p>
      </div>
      <div>
        <ul class="card-weather list-inline">
          <li>
            <% if r.weather_type == "clear"%>
              <%= icon_weather("clear") %>
            <% elsif r.weather_type == "clouds"%>
              <%= icon_weather("clouds") %>
            <% elsif r.weather_type == "rain"%>
              <%= icon_weather("clear") %>
              <%= icon_weather("clouds") %>
              <%= icon_weather("rain") %>
            <% elsif r.weather_type == "drizzle"%>
              <%= icon_weather("clear") %>
              <%= icon_weather("clouds") %>
            <% elsif r.weather_type == "storm"%>
              <%= icon_weather("clear") %>
              <%= icon_weather("drizzle") %>
              <%= icon_weather("rain") %>
              <%= icon_weather("thunderstorm") %>
            <% end %>
          </li>
        </ul>
        <% if params[:latitude].present? %>
          <div class="text-right distance">
            <%= (r.distance_from([params[:latitude],params[:longitude]], :km) * 1000).round %> m <i class="fa fa-map-marker"></i>
          </div>
        <% end %>

      </div>
    </div>
  </div>
  <div class="card-footer">
  </div>
</div>


<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
   <div id="footer">
    <ul class="list-inline">
      <li><a href=""><i class="fa fa-youtube"></i></a></li>
      <li><a href=""><i class="fa fa-instagram"></i></a></li>
      <li><a href=""><i class="fa fa-facebook"></i></a></li>
      <li><a href=""><i class="fa fa-twitter"></i></a></li>
    </ul>
    <p>Made with 🖕 @ LeWagon</p>
  </div>

app/views/shared/_form.html.erb
<div class="search-wrapper text-center">
  <div class="container">
    <div class="form-inline">
      <%= form_tag(recommendations_path, :method => 'get', id: 'search-form') do |f| %>
        <div class="form-group">
          <%= text_field_tag :city, params[:search], placeholder: "Enter a new address", class:"form-control input-lg" %>
          <%= hidden_field_tag :latitude %>
          <%= hidden_field_tag :longitude %>
        </div>
        <%= submit_tag "Search", class: "btn btn-warning btn-lg"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo18.png" %>
  <% end %>

  <!-- Right Navigation -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Notification -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Edit my Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_bookmarks_path(current_user) do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "My Bookmarks") %>
              <% end %>
            </li>
            <li>
              <%= link_to user_ratings_path(current_user) do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "My Ratings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
            </div>
          </div>
          </div>
    <% else %>
  <div class="navbar-wagon-right hidden-sm hidden-xs">
    <div class="navbar-wagon-item">
      <div class="dropdown">
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Register"), new_user_registration_path, class: "navbar-wagon-link btn btn-default" %>

      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn btn-default" %>
        </div>
      </div>
  </div>
    <% end %>

    <!-- Button (call-to-action) -->

    <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-right hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown" href="#"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <% if user_signed_in? %>
          <li>
            <%= link_to user_profile_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Edit my Profile") %>
            <% end %>
          </li>
            <li>
                <%= link_to user_bookmarks_path(current_user) do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "My Bookmarks") %>
                <% end %>
              </li>
              <li>
                <%= link_to user_ratings_path(current_user) do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "My Ratings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
        <% else %>
          <li>
            <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>

</div>

app/views/shared/_ratings.html.erb
<%= link_to recommendation_path(r), :class => "link" do%>
<div class="card">
  <div class="card-body">
    <div class="card-picture" style="background-image: url('<%= cl_image_path(r.photo, width: 500, height: 300) %>')">
    </div>
    <div class="card-infos">
      <div class="card-title">
        <h3><%= r.name.truncate(25) + "..." %></h3>
        <p class="rating"><%= rating_for r, "rating", disabled: true, star_path: '/images/ratyrate' %></p>
      </div>
      <div>
        <ul class="card-weather list-inline">
        </ul>
      </div>
    </div>
  </div>
  <div class="card-footer">
  </div>
</div>
<% end %>

app/views/shared/_recommendation.html.erb
<%= link_to recommendation_path(r), :class => "link" do%>


<div class="card">
  <div class="card-body">
    <div class="card-picture" style="background-image: url('<%= cl_image_path(r.photo, width: 500, height: 300) %>')">
      <div class="card-hover">
        <ul class="list-inline text-center hover-btns">
          <li>
            <%= form_tag recommendation_bookmarks_path(r), method: :post, id: "bookmark_form_#{r.id}" do %>
              <%= link_to "javascript:$('#bookmark_form_#{r.id}').submit()", class: "disabled" do %>
                <i class="fa fa-bookmark"></i>
              <% end %>
            <% end %>
            <h3>Save for later</h3>
          </li>
          <li>
            <%= link_to "http://maps.google.com/maps?saddr=#{params[:latitude]},#{params[:longitude]}&daddr=#{r.latitude},#{r.longitude}&ie=UTF8&dirflg=w", :target => '_blank', class: "disabled"  do %>
              <i class="fa fa-map"></i>
            <% end %>
            <h3>Go there</h3>
          </li>
          <li>
            <%= link_to recommendation_path(r), class: "disabled"  do %>
              <i class="fa fa-eye"></i>
            <% end %>
            <h3>More info</h3>
          </li>
        </ul>
      </div>
    </div>
    <div class="card-infos">
      <div class="card-title">
        <h3><%= r.name.truncate(25) + "..." %></h3>
        <p class="rating"><%= rating_for r, "rating", disabled: true, star_path: '/images/ratyrate' %></p>
      </div>
      <div>
        <ul class="card-weather list-inline">
          <li>
            <% if r.weather_type == "clear"%>
              <%= icon_weather("clear") %>
            <% elsif r.weather_type == "clouds"%>
              <%= icon_weather("clouds") %>
            <% elsif r.weather_type == "rain"%>
              <%= icon_weather("clear") %>
              <%= icon_weather("clouds") %>
              <%= icon_weather("rain") %>
            <% elsif r.weather_type == "drizzle"%>
              <%= icon_weather("clear") %>
              <%= icon_weather("clouds") %>
            <% elsif r.weather_type == "storm"%>
              <%= icon_weather("clear") %>
              <%= icon_weather("drizzle") %>
              <%= icon_weather("rain") %>
              <%= icon_weather("thunderstorm") %>
            <% end %>
          </li>
        </ul>
        <% if params[:latitude].present? %>
          <div class="text-right distance">
            <%= (r.distance_from([params[:latitude],params[:longitude]], :km) * 1000).round %> m <i class="fa fa-map-marker"></i>
          </div>
        <% end %>

      </div>
    </div>
  </div>
  <div class="card-footer">
    <% unless User.find(r.user_id).first_name.nil? %>
      <%= image_tag User.find(r.user_id).facebook_picture_url , class: "avatar" %>
      <a href="#"><%= User.find(r.user_id).first_name %></a>
    <% end %>

  </div>
</div>


<% end %>