config/routes.rb
Rails.application.routes.draw do
  get 'user/show'

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,
    controllers: { registrations: 'registrations',
                   omniauth_callbacks: 'users/omniauth_callbacks'
                 }
  root to: 'pages#home'

  resources :recommendations do
    resources :bookmarks, only: [:create, :index, :delete]
  end

  get 'users/:id/show', to: 'users#show', as: 'user_profile'
  get 'users/:id/bookmarks', to: 'users#user_bookmarks', as: 'user_bookmarks'
  get 'users/:id/ratings', to: 'users#user_ratings', as: 'user_ratings'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recommendations, only: [ :create ]
    end
  end

end

app/views/pages/_homebackup.html.erb
<div class="row" id="banner-wrapper" >
  <div class="text-center col-xs-12 banner" id="banner-img" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%=image_path('thunder.jpg') %>);">
    <div id="canvasHolder">
      <div id="canvas">
        <div class="banner-content">
          <h1>Don't let the weather fuck your vacations</h1>
          <div class="btn-wrapper">
            <div id="load-msg"></div>
            <%= link_to "Fuck the weather!!!", "#", id: "myRecos", class:"btn btn-lg btn-danger", data: { loading_text: "Loading..."} %>
          </div>
      <% if user_signed_in? %>
        <p>Logado</p>
      <% else %>
        <%= link_to "Register", new_user_registration_path, remote: true, 'data-toggle' => 'modal', 'data-target' => '#signUpModal', method: :get %>
        <%= link_to "Login", new_user_session_path, remote: true, 'data-toggle' => 'modal', 'data-target' => '#logInModal', method: :get %>
      <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'modal' %>
<%= render 'login_modal' %>

app/views/pages/_login_form.html.erb
<%= simple_form_for(:user, url: user_session_path) do |f| %>
<%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :email, required: false, class:"form-control", autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.input :password, class:"form-control", required: false %>
    </div>
    <div class="form-group">
      <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
    </div>
    <div class="modal-footer">
      <ul class="text-center list-inline">
        <li >
          <div class="form-actions btn-block" style="margin-right:20px" >
            <%= f.button :submit, "Login" %>
          </div>
        </li>
        <li>
          <%= link_to user_facebook_omniauth_authorize_path() do %>
            <div class=" btn btn-default btn-social btn-facebook">
              <i class="fa fa-facebook"></i>Login with Facebook
            </div>
          <% end %>
        </li>
      </ul>
  </div>
  </div>

<% end %>

app/views/pages/_login_modal.html.erb
<div class="modal-wrapper">
<div class="modal fade custom" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-center" id="myModalLabel">Sign Up</h4>
          </div>
        <div class="modal-body">
          <%= render 'login_form' %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/_modal.html.erb
<div class="modal-wrapper">
<div class="modal fade custom" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-center" id="myModalLabel">Sign Up</h4>
          </div>
        <div class="modal-body">
          <%= render 'signup_form' %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/_signup_form.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :email, required: true, autofocus: true, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.input :password, class:"form-control", required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    </div>
    <div class="form-group">
      <%= f.input :password_confirmation, required: true, class:"form-control" %>
    </div>
    <div class="modal-footer">
      <ul class="text-center list-inline">
        <li >
          <div class="form-actions btn-block" style="margin-right:20px" >
            <%= f.button :submit, "Sign up" %>
          </div>
        </li>
        <li>
          <%= link_to user_facebook_omniauth_authorize_path() do %>
            <div class=" btn btn-default btn-social btn-facebook">
              <i class="fa fa-facebook"></i>Sign up with Facebook
            </div>
          <% end %>
        </li>
      </ul>
  </div>
  </div>

<% end %>

app/views/pages/home.html.erb
<div id="home">

  <img id="background"/>
  <!-- <canvas id="canvas"></canvas> -->
  <div class="container text-center">
    <h1>Don't let the weather fuck your vacations</h1>
    <div id="ftw">
      <%= link_to "Fuck the weather", "#", id: "myRecos", class:"btn btn-lg btn-danger", data: { loading_text: "Loading..."} %>
    <div id="load-msg">
    <% if user_signed_in? %>

    <% else %>
      <%= link_to "Register", new_user_registration_path, class:"btn btn-default", remote: true, 'data-toggle' => 'modal', 'data-target' => '#signUpModal', method: :get %>
        <%= link_to "Login", new_user_session_path, remote: true, 'data-toggle' => 'modal', 'data-target' => '#logInModal', method: :get, class:"btn btn-success" %>
    <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'modal' %>
<%= render 'login_modal' %>

<% content_for(:after_js) do %>
  <script>
  $(document).ready(run())
  function testLink() {
  if ($("#myRecos").attr("href") == "#") {
    $("#myRecos").hide()
    $("#load-msg").html("<h3>Getting your location...</h3>");
    console.log($("#myRecos").attr("href"))
    setTimeout(testLink, 0500);
  } else {
    $("#load-msg").hide();
    // $("#myRecos").show();
  }
};
  $("#myRecos").click(function() {
  testLink();
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var lat = position.coords.latitude;
      var lon = position.coords.longitude;
      var url = '<%="#{recommendations_path}?longitude=" %>' + lon + "&latitude=" + lat;
      $("#myRecos").attr("href", url);
      window.location = url;
    })
  };
})

  </script>
<% end %>